In [7]:
import math

def basic_sigmoid(x):
    s= 1/(1+((math.e)**(-x)))
    return s
print(basic_sigmoid(2))



0.8807970779778823


In [13]:
import numpy as np

In [16]:
import numpy as np

python_list = [1, 2, 3, 4, 5, 6]
numpy_array = np.array([1, 2, 3, 4, 5, 6])

squared_list=[]

for number in python_list:
    squared_list.append(number**2)
print(squared_list)


[1, 4, 9, 16, 25, 36]


In [17]:
def numpy_sigmoid(x):
  s = 1/(1+(np.exp(-x)))
  return s
print(numpy_sigmoid(2))


0.8807970779778823


In [29]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

def normalize_array(arr):
  min_val = arr.min(axis=0)
  max_val = arr.max(axis=0)
 
  numerator = arr - min_val
  denominator = max_val -min_val
  normalized_array = numerator/denominator
  return normalized_array

normalized_array = normalize_array(arr)
print("Original Array:")
print(arr)
print("\nNormalized Array:")
print(normalized_array)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized Array:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
