# Introduction to Deep Learning
This assignment will give you brief introduction to NumPy. NumPy is a fundamental package for scientific computing in Python. It provides support for arrays, matrices, and mathematical functions, making it essential for various fields including data science, machine learning, and engineering.

Sigmoid function is definded as
$$
sigmoid(x) = \frac{1}{1 + e^{-x}}
$$
Let's start by writing a function in python that will compute this for us 

#### Exercise
Complete the sigmoid function given below using basic python math library  
Hint: use `math.exp()` for exponential function or `math.e` for value of e = 2.718281828459045…

In [21]:
import math

def basic_sigmoid(x):
  # This function should return value for sigmoid(x)
  s = 1/(1+math.exp((-1)*x))
  return s

In [22]:
# sigmoid(2) is approx 0.88079
print(basic_sigmoid(2))

0.8807970779778823


## Numpy
Let's start by importing NumPy  
Here we are importing numpy as np so we won't have to write numpy everytime and this np notation is very standard and used widely  
Run the code below to import numpy 

In [23]:
import numpy as np

### NumPy Arrays
We can initialize a numpy array by `np.array()`  
Run the code below to get a numpy array from a python list

In [24]:
# initialize a python list
python_list = [1, 2, 3, 4, 5, 6]
# initiatlize a numpy array
numpy_array = np.array([1, 2, 3, 4, 5, 6])

# let's print both of them
print(python_list)
print(numpy_array)


[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


#### Exercise
Let's say we want to square each and every element of our python list, we write a loop to do so  
Complete the code below to do so

In [25]:
squared_list = []

for number in python_list:
  squared_list.append(number**2)

# This should print a list with each element
# squared of python_list
print(squared_list)

[1, 4, 9, 16, 25, 36]


Some of you might want to do this instead

In [26]:
squared_list = [x**2 for x in python_list]
print(squared_list)

[1, 4, 9, 16, 25, 36]


But working with basic list in python, we need to write explicit for loops for even such basic stuff  
If we want to do the same for NumPy array, we can just write

In [27]:
squared_array = numpy_array**2
print(squared_array)

[ 1  4  9 16 25 36]


This is just the starting of the magic NumPy can do for you

#### Exercise
Let's code sigmoid function using numpy
$$
sigmoid(x) = \frac{1}{1 + e^{-x}}
$$
Hint: use `np.exp()` for exponential function

In [28]:
def numpy_sigmoid(x):
  s = 1/(1+np.exp(-x))
  return s

In [29]:
# sigmoid(2) is approx 0.88079
print(numpy_sigmoid(2))

0.8807970779778823


Now as you have coded sigmoid function using basic math library and numpy library, what if we want to get sigmoid of each element of a list

For the function we wrote using basic math library, we need to write a for loop to get this done  
Run the code below

In [30]:
python_list = [1, 2, 3, 4, 5, 6]

sigmoid_list = [basic_sigmoid(x) for x in python_list]

print(sigmoid_list)

[0.7310585786300049, 0.8807970779778823, 0.9525741268224334, 0.9820137900379085, 0.9933071490757153, 0.9975273768433653]


But numpy makes it easy for you

In [31]:
numpy_array = np.array([1, 2, 3, 4, 5, 6])

sigmoid_array = numpy_sigmoid(numpy_array)

print(sigmoid_array)

[0.73105858 0.88079708 0.95257413 0.98201379 0.99330715 0.99752738]


Writing a for loop might not seem very tough for now but just imagine you want to appy same operation or function on easy element of a 3D array (eg. an image) or a 4D array (eg. group of images)  
but for any n-dimentional numpy array you can just write your own coded `numpy_sigmoid(array)` function  

## Broadcasting
Broadcasting is a powerful feature of NumPy that allows arithmetic operations to be performed on arrays of different shapes. This eliminates the need for explicit looping over array elements, making code more concise and efficient.  
### Broadcasting Rules
NumPy follows strict rules to determine whether two arrays are compatible for broadcasting:

1. If the arrays do not have the same number of dimensions, NumPy will pad the smaller shape with ones on its leading (left) side.
2. If the shape of the arrays does not match in any dimension, NumPy will stretch the dimension with size 1 to match the other shape.  

Let's see this in action, just run the blocks below and learn by seeing the result

In [32]:
# Create an array
arr = np.array([1, 2, 3, 4])

# Add a scalar value to the array
result = arr + 10

print("Array:", arr)
print("Result:", result)

Array: [1 2 3 4]
Result: [11 12 13 14]


Let's see another example

In [33]:
# Create two arrays with different shapes
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

# Add the arrays
result = arr1 + arr2

print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Result:")
print(result)

Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[10 20 30]
Result:
[[11 22 33]
 [14 25 36]]


#### Exercise
Normalizing nd-array  
Complete the code below to return array with it's values normalized without using any explicit for loop and using broadcasting functionality
$$
normalized\_value = \frac{{ value - \text{{min\_val}}}}{{\text{{max\_val}} - \text{{min\_val}}}}
$$
With broadcasting in action we can write this as 
$$
normalized\_array = \frac{{ array - \text{{min\_val}}}}{{\text{{max\_val}} - \text{{min\_val}}}}
$$
For each element we want to replace it with this new value  
Hint: use `np.min()` and `np.max()` 

In [34]:
def normalize_array(arr):
  
  """Normalize an n-dimensional array using broadcasting."""

  min_val = np.min(arr)
  max_val = np.max(arr)
  numerator = arr-min_val
  denominator = max_val-min_val

  normalized_array = numerator / denominator
  return normalized_array

In [35]:
# Create a sample 2D array
sample_array = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])

# Normalize the array
normalized_array = normalize_array(sample_array)
print("Original Array:")
print(sample_array)
print("\nNormalized Array:")
print(normalized_array)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized Array:
[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


## Reshaping arrays
Reshaping arrays is a crucial operation in NumPy that allows you to change the shape or dimensions of an array without changing its data. This operation is essential for various tasks in data manipulation and analysis.

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)

print("Original Array:")
print(arr)
print("Reshaped Array:")
print(reshaped_arr)

Original Array:
[1 2 3 4 5 6]
Reshaped Array:
[[1 2 3]
 [4 5 6]]


Let's see one more example

In [37]:
# this will create a 1D array with values from 1 to 16
arr = np.arange(1, 17)
print("Original Array", arr)

# let's reshape this array in shape (4, 4) and see the results
reshaped_arr = arr.reshape(4, 4)
print("Reshaping with arguments (4,4)", reshaped_arr)

# you can also set the one of the arguments in reshape to -1
# and python will handle the value for you
reshaped_arr = arr.reshape(4, -1)
print("Reshaping with arguments (4,-1)", reshaped_arr)

Original Array [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Reshaping with arguments (4,4) [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Reshaping with arguments (4,-1) [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


You'll work more with reshaping arrays in next assignments where we will be reshaping iamges (3D arrays) into 1D arrays for our convenience.